version: '0.0.0+build.{build}'
environment:
  
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"

  - "python -m pip install --upgrade pip"
  - cmd: pip install -r requirements.txt

build_script:
  - cmd: flake8 .
  - cmd: nosetests
 
