version: '1.0.{build}'
environment:
  matrix:
    - TARGET: python36
      PYTHON: 'C:\\Python-36-x64'
      PYTHON_VERSION: 3.6.5
      PYTHON_ARCH: 64


init:
  - "ECHO %PYTHON% %vcvars% (%bits%)
  - python -c "import sys;print('Python version is {}'.format(sys.version))"
  - python -m pip install -U nose'

build_script:
  - cmd: |
      set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\build\libgit2
      git clone --depth=1 -b maint/v0.27 https://github/com/libgit2/libgit2.git libgit2
      mkdir build
      cd build
      cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
      cmake --build . --config Release --target install
      cd ..

install:
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
  - cmd: flake8 .
  - cmd: nosetests
 
