version: '0.0.0+build.{build}'
image: Visual Studio 2015
branches:
  only:
    - master

environment:
    
  matrix:
    - GENERATOR: "Vistal Studio 14 Win64"
      PYTHON: "C:\\Python36-x64\\python.exe"


build_script:
  - cmd: |
      set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\build\libgit2
      git clone --depth=1 -b maint/v0.27 https://github/com/libgit2/libgit2.git libgit2
      mkdir build
      cd build
      cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
      cmake --build . --config Release --target install
      cd ..
    
install:
  - $env:LIBGIT2 = ($Env:APPVEYOR_BUILD_FOLDER + "\build\libgit2")
    &$env:PYTHON --version
    &$env:PYTHON -m pip install -r requirements.txt

build_script:
  - cmd: flake8 .
  - cmd: nosetests
 
