version: '1.0.{build}'
environment:
  matrix:
    - GENERATOR: 'Visual Studio 14 Win64'
      PYTHON: 'C:\Python36-x64'       
init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\python -m pip install -U nose"

build_script:
  - cmd: |
      set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\build\libgit2
      git clone --depth=1 -b maint/v0.27 https://github.com/libgit2/libgit2.git libgit2
      mkdir build
      cd build
      cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
      cmake --build . --config Release --target install
      cd ..
  - cmd: mkdir _repos

install:
  - cmd: "%PYTHON%\\python -m pip install -r requirements.txt"

test_script:
  - cmd: flake8 .
  - cmd: nosetests
 
