version: '1.0.{build}'
image: Visual Studio 2017
environment:
  matrix:
     PYTHON: 'C:\Python-36-x64'
     PYTHON_VERSION: 3.6.5
     PYTHON_ARH: 64


init:
  - cmd: '%PYTHON% -m pip install -U nose'

build_script:
  - cmd: |
      set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\build\libgit2
      git clone --depth=1 -b maint/v0.27 https://github/com/libgit2/libgit2.git libgit2
      mkdir build
      cd build
      cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
      cmake --build . --config Release --target install
      cd ..

install:
  - cmd: python -m pip install -r requirements.txt

test_script:
  - cmd: flake8 .
  - cmd: nosetests
 
